name: OriginXWhitelist
version: '1.0.0'
main: cc.originx.lrd1122.OriginXWhitelist
api-version: '1.20'
authors: [ lrd1122 ]
commands:
  owhitelist:
    description: 白名单管理命令
    usage: /owhitelist
    aliases: ow
    permission: originxwhitelist.admin

permissions:
  originxwhitelist.admin:
    description: 允许使用白名单管理命令
    default: op